import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './styles/global.scss'
import styles from "@/app/styles/layout.module.scss";
import {Aside} from "@/app/containers/aside/Aside";
import {Background} from "@/app/components/background/Background";
import {Video} from "@/app/components/video/Video";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={styles.page}>
            {children}
            <Aside/>
        </div>
        <>
            <Background/>
            <Video/>
        </>
        </body>
        </html>
    )
}
